# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.cache/wt [current_project]
set_property parent.project_path S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/komponenter/SR4.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/komponenter/MUX2x8.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/labbfiler/cpu_pkg.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/komponenter/REG8.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/labbfiler/stack.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/labbfiler/registerblock.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/komponenter/REG6.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/komponenter/MUX3x6.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/komponenter/ALU8.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/misc/sub10.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/misc/edge_det.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/misc/clk_divider.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/labbfiler/instruktionsavkodare.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/labbfiler/berakningsenhet.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/labbfiler/adressvaljare.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/misc/nbcd.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/misc/BCD_driver.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/misc/debouncer.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/labbfiler/minne.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/labbfiler/IOblock.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/labbfiler/debugmodul.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/labbfiler/cpu.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/misc/reset_block.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/labbfiler/klockblock.vhd
  S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/sources_1/imports/LabMCU_16_17/labbfiler/mcu.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/constrs_1/imports/misc/Nexys4_Master.xdc
set_property used_in_implementation false [get_files S:/Courses/eit/EITA15/Laborationer/Lab5/lab5.srcs/constrs_1/imports/misc/Nexys4_Master.xdc]


synth_design -top mcu -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mcu.dcp

catch { report_utilization -file mcu_utilization_synth.rpt -pb mcu_utilization_synth.pb }
